spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
logging.level.org.springframework.security=DEBUG

# SQL scripts for schema and data initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:/schema.sql
spring.sql.init.data-locations=classpath:/data.sql

# --- Cloudinary ---
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# --- Cloudinary ---（ローカルではダミーでOK！）
#cloudinary.cloud-name=dummy
#cloudinary.api-key=123456789012345
#cloudinary.api-secret=dummysecret1234567890

# --- Stripe ---
stripe.api.secretKey=${STRIPE_SECRET_KEY}
stripe.public.key=${STRIPE_PUBLIC_KEY}

# --- LINE Notify ---
line.notify.api.url=https://notify-api.line.me/api/notify
line.notify.token=${LINE_NOTIFY_TOKEN}
# --- Stripe ---
#stripe.api.secretKey=test
#stripe.public.key=pk_test_dummy

# --- LINE Notify ---
#line.notify.token=dummy